services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_cache:/var/cache/nginx
    depends_on:
      - app
    networks:
      - app_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "3000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
    nginx_cache:
        driver: local
