services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_cache:/var/cache/nginx
      - ./certbot/conf:/etc/letsencrypt  # Certbot certificates
      - ./certbot/www:/var/www/certbot    # Webroot for Certbot challenges
    depends_on:
      - app
      - certbot
    networks:
      - app_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # Certbot certificates
      - ./certbot/www:/var/www/certbot    # Webroot for Certbot challenges
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $!; certbot renew; done'"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "3000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
    nginx_cache:
        driver: local
